services:
  db:
    image: postgres:15
    container_name: market_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser 
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: market_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
