name: Build Docs PDF w/ LateX

on:
  workflow_dispatch:   # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc + XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Build PDF
        run: pandoc docs/*.md -o docs.pdf --pdf-engine=xelatex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: docs.pdf